INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_cpu_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','CPU利用率', '交换机服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '','switch_cpu_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_memory_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','内存利用率', '交换机服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '','switch_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_memory_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','内存利用率', 'Linux服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_cpu_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','CPU利用率', 'Linux服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_cpu_usage', '0~100','', '6.6','6.6');

INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_cpu_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','CPU利用率', '交换机服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '','switch_cpu_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_memory_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','内存利用率', '交换机服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '','switch_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_memory_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','内存利用率', 'Linux服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_cpu_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','CPU利用率', 'Linux服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_cpu_usage', '0~100','', '6.6','6.6');

INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_cpu_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','CPU利用率', '交换机服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '','switch_cpu_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_memory_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','内存利用率', '交换机服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '','switch_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_memory_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','内存利用率', 'Linux服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_cpu_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','CPU利用率', 'Linux服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_cpu_usage', '0~100','', '6.6','6.6');

INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_cpu_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','CPU利用率', '交换机服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '','switch_cpu_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_memory_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','内存利用率', '交换机服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '','switch_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_memory_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','内存利用率', 'Linux服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_cpu_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','CPU利用率', 'Linux服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_cpu_usage', '0~100','', '6.6','6.6');

INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_cpu_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','CPU利用率', '交换机服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '','switch_cpu_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_memory_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','内存利用率', '交换机服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '','switch_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_memory_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','内存利用率', 'Linux服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_cpu_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','CPU利用率', 'Linux服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_cpu_usage', '0~100','', '6.6','6.6');

INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_cpu_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','CPU利用率', '交换机服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '','switch_cpu_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('switch_memory_usage', 'com.sugon.acx.collector.app.switches.collector.impl.SwitchCollectorImpl','内存利用率', '交换机服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '','switch_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_memory_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','内存利用率', 'Linux服务区内存利用率', 1, '%','memory', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_memory_usage', '0~100','', '6.6','6.6');
INSERT INTO gv_collection_metric (name, collector, display_name ,description ,data_type, unitpart_type ,collect_interval ,iscollect, pre_process, post_process, collect_mode, batch_group, priority, collect_protocol, protocol_param, value_keyword, value_range, value_mapping, introduced_version, last_modify_version) VALUES ('linux_cpu_usage', 'com.sugon.acx.collector.app.oslinux.collector.impl.OslinuxCollectorImpl','CPU利用率', 'Linux服务区CPU利用率', 1, '%','cpu', 90, 1, '','', 1,'group1', 0,'null', '/linux/monitor/main','linux_cpu_usage', '0~100','', '6.6','6.6');

